// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fit_model_cv_cpp
List fit_model_cv_cpp(NumericVector x, NumericVector y, std::string model_type, std::string select_metric);
RcppExport SEXP _smartcurvefit_fit_model_cv_cpp(SEXP xSEXP, SEXP ySEXP, SEXP model_typeSEXP, SEXP select_metricSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< std::string >::type model_type(model_typeSEXP);
    Rcpp::traits::input_parameter< std::string >::type select_metric(select_metricSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_model_cv_cpp(x, y, model_type, select_metric));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_smartcurvefit_fit_model_cv_cpp", (DL_FUNC) &_smartcurvefit_fit_model_cv_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_smartcurvefit(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
