# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fit_model_cpp <- function(x, y, model_type, start_params, a_min = 0.5, a_max = 2.0, b_min = 0.5, b_max = 2.0, step = 0.1) {
    .Call(`_smartcurvefit_fit_model_cpp`, x, y, model_type, start_params, a_min, a_max, b_min, b_max, step)
}

