# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fit_model_cv_cpp <- function(x, y, model_type, select_metric) {
    .Call(`_smartcurvefit_fit_model_cv_cpp`, x, y, model_type, select_metric)
}

